### ISSUE TITLE
Create 'ci' and 'prod' aliases automatically if they don't already exist

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/aws-lambda-deploy#32]
As well as deploying, it would be useful if dpl could also 
- create 'ci' alias pointing to $LATEST if 'ci' doesn't already exist
- create 'prod' alias if it doesn't already exist
- publish a new version of $LATEST (if v1 doesn't already exist) and assign it to 'prod'. 
:)

**Comment by nelsonic** [comment]
@nikhilaravi I briefly discussed this with @plaenen on Friday...
We are thinking of having a totally *separate* AWS Account on AWS so that we can get around this whole CI/PROD thing.
The *biggest* advantage is the security benefit of having an isolated Production environment which means that no developers or un-audited 3rd Parties (e.g. CodeShip) have access to production data, given that we expect to store *some* form of customer info at some point for personalisation...

**Comment by nikhilaravi** [comment]
@nelsonic ah okay. so would CI code be on one account and PROD on another?

**Comment by nelsonic** [comment]
@nikhilaravi that would be the *idea*. But that will require us to re-jig our deployment a bit... 
it might be an idea to add CI/PROD to the name of the Function temporarily...

**Comment by nelsonic** [comment]
@nikhilaravi I suspect this is no longer relevant. please re-open if still required. thanks!
